### ISSUE TITLE
Elixir hands-on portal

### ISSUE THREAD

**Issue by ymtszw** [access-company/server_training#3]
(2018/05)

- Elixir基礎ハンズオンでは、ちょっとしたCLIを作ってもらう予定です
- 作ったコードはそれぞれのGitHubアカウントにrepositoryを作ってpushし、repositoryへのリンクをこのissueにpostしてください
- 終了後、どんな感じになったか私の方でざっと確認＆多少フォローアップしようと思います
- 質問等をpostしてもらっても構いません

**Comment by abailinrun** [comment]
https://github.com/aBaiLinrun/server_training_app

**Comment by ttokit** [comment]
https://github.com/ttokit/HipChat_CLI

**Comment by aKantaTakeuchi** [comment]
https://github.com/aKantaTakeuchi/TrainingServer

**Comment by aShihoOmine** [comment]
https://github.com/aShihoOmine/Training_myapp

**Comment by aNobuhisaMasaki** [comment]
https://github.com/aNobuhisaMasaki/elixir_cli

**Comment by hey3** [comment]
https://github.com/hey3/Training_elixir

**Comment by aRhezaHarliman** [comment]
https://github.com/aRhezaHarliman/elixir_training

**Comment by ka-clmx** [comment]
https://github.com/ka-clmx/hipchat_elixir

**Comment by naru-hiyoko** [comment]
成沢です。新卒研修の途中経過です。ヒップチャットにメッセージ送信まで完了しました。よろしくお願いします。[https://github.com/naru-hiyoko/ServerTrainingHipChat](url)

**Comment by aPuYue** [comment]
PU YUEです。よろしくお願いいたします。https://github.com/aPuYue/-CLI-

**Comment by aYukitoshiSato** [comment]
https://github.com/aYukitoshiSato/TariningElixir

**Comment by ymtszw** [comment]
皆様お疲れ様でした。後ほど確認させて頂きます。
